name: camera_example
description: Demonstrates how to use the camera plugin.

dependencies:
  camera:
    path: ../

  flutter:
    sdk: flutter
  video_player: ^0.10.0
  integration_test:
    path: ../../integration_test

  permission_handler: "^5.0.1+1"
  path: "^1.7.0"
  path_provider: "^1.6.11"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4 <2.0.0"
